# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douentza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotlinerequest',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Call duration (seconds)', null=True, verbose_name='Callback duration'),
        ),
        migrations.AlterField(
            model_name='hotlinerequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='requests', to='douentza.Tag', verbose_name='Tags'),
        ),
    ]
