# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('douentza', '0002_auto_20160525_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalrequest',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cacheddata',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='callbackattempt',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotlinerequest',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotlinerequest',
            name='operator',
            field=models.CharField(blank=True, choices=[('orange', 'Orange MALI'), ('malitel', 'Malitel'), ('foreign', 'Ext\xe9rieur')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveytaken',
            name='taken_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
